---
services:
  zitadel-login:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zitadel-login-ui
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LANGUAGE=fr
      - LOCALE=fr-FR
      - TZ=Europe/Paris
      - ZITADEL_API_URL=${ZITADEL_API_URL}
      - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
      - CUSTOM_REQUEST_HEADERS=HOST:${EXTERNAL_DOMAIN}
      - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}
      - ZITADEL_SERVICE_USER_TOKEN=${ZITADEL_SERVICE_USER_TOKEN_FILE}
    user: '0'
    volumes: [../files/zitadel:/current-dir:ro]
    networks: [dokploy-network]
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --tries=1
        - --spider
        - http://localhost:3000/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  dokploy-network:
    external: true
